1. Crie dois NumPy Arrays unidimensionais de tamanho 8: um formado apenas por 1’s e outro formado por números aleatórios entre 0 e 9. Some estes dois NumPy Arrays e guarde o resultado dentro de um terceiro NumPy Array. Por fim, faça o seguinte:
a. Se a soma de todos os elementos do Array resultante for >= 40, remodele este NumPy Array para se tornar uma matriz com mais linhas do que colunas. Senão, remodele para que se torne uma matriz com mais colunas do que linhas.

In [2]:
import numpy as np

ones = np.ones(8)
random = np.random.randint(0,10,8)
soma = ones + random

if soma.sum() >= 40:
    mtz = soma.reshape(4,2)
else: 
    mtz = soma.reshape(2,4)
print(mtz)

[[2. 6. 8. 6.]
 [1. 2. 5. 9.]]


2. Crie dois NumPy Arrays unidimensionais: um de números pares de 0 à 51 e outro também de números pares de 100 até 50. Em seguida,  os concatene e mostre os resultados ordenados

In [25]:
array1 = np.arange(0, 52, 2)
array2 = np.arange(100, 49, -2)

arrayFinal = np.sort(np.concatenate((array1, array2)))
print(arrayFinal)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  50  52  54  56  58  60  62  64  66  68
  70  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


3. Mini Campo Minado:
a) Crie um NumPy Array 2 x 2 formado apenas por 0’s
b) Em seguida, adicione um número 1 em uma posição aleatória desta matriz;
c) Faça uma entrada de dados para solicitar o usuário que faça uma jogada(selecione uma posição da matriz) 
I. Se ele selecionar todas as posições em que o número 1 não se encontra, mostre a  mensagem “Congratulations! You beat the game!”
II. Senão, se dentro das 3 primeiras jogadas ele achar o número 1, mostre a mensagem “Game Over! Try Again! ”

In [16]:
campo = np.zeros((2,2))
x, y = np.random.randint(0, 2, 2)
campo[x][y] = 1
encontrou = False
for i in range (3):
    entrada = input("Faça sua jogada, entre com a posição da matriz (x,y): ")
    x, y = entrada.split(',')
    if campo[int(x)][int(y)] == 1:
        encontrou = True
        print("Game Over!")
        break

if not encontrou:
    print("Congratulations! You beat the game!")
print(campo)

Game Over!
[[1. 0.]
 [0. 0.]]


4. Crie uma matriz de tamanho qualquer. Extraia seu número de linhas e colunas, multiplique-os, e diga se esta matriz poderia se tornar um vetor unidimensional com número par ou ímpar de elementos 

In [22]:
matriz = np.random.randint(0, 10, (4,4))
tamanho = matriz.shape[0]*matriz.shape[1]
if tamanho % 2 ==0:
    print("A matriz se tornaria um vetor unidimensional par de tamanho:", tamanho)
else:
    print("A matriz se tornaria um vetor unidimensional ímpar de tamanho:", tamanho)

A matriz se tornaria um vetor unidimensional par de tamanho: 16


5. Crie uma matriz de tamanho 4x4 formada por números aleatórios inteiros entre 1 e 50 (use seed = 10 antes) 
a) Mostre o resultado da média de cada linha e cada coluna da matriz gerada
b) Apresente o maior valor das médias das linhas e também das colunas
c) Mostre a quantidade de aparições de cada um dos números gerados na matriz. Em seguida, mostre apenas os números que aparecem 2 vezes


In [55]:
np.random.seed(10)
matriz = np.random.randint(1, 51, (4,4))
print(matriz)

print("Média de cada linha", matriz.mean(axis=1))
print("Média de cada coluna", matriz.mean(axis=0))

print("Maior valor da media das linhas:", matriz.mean(axis=1).max())
print("Maior valor da media das colunas:", matriz.mean(axis=0).max())

numbers, count = np.unique(matriz, return_counts=True) # retorna dois arrays, um com os números e outro com a quantidade de vezes que cada número aparece
print("Quantidade de aparições de cada número na matriz:")
for i in range(len(numbers)):
    print(numbers[i], ":", count[i])

print("Números que aparecem duas vezes na matriz:")
for i in range(len(numbers)):
    if count[i] == 2:
        print(numbers[i])

[[10 37 16  1]
 [50 29 26 30]
 [49 30 50  9]
 [10  1 43 41]]
Média de cada linha [16.   33.75 34.5  23.75]
Média de cada coluna [29.75 24.25 33.75 20.25]
Maior valor da media das linhas: 34.5
Maior valor da media das colunas: 33.75
Quantidade de aparições de cada número na matriz:
1 : 2
9 : 1
10 : 2
16 : 1
26 : 1
29 : 1
30 : 2
37 : 1
41 : 1
43 : 1
49 : 1
50 : 2
Números que aparecem duas vezes na matriz:
1
10
30
50
